### ISSUE TITLE
Theme Causing Visual Editor Tab Issues

### ISSUE THREAD

**Issue by foodin65** [MIGHTYminnow/trestle#13]
Hey @MickeyKay,

I'm not sure if this is the appropriate space to post this, I apologize in advance if that's the case. 

But I just downloaded your theme and installed it on a fresh WPEngine install of Wordpress 4.2.2. Upon activation of this theme the Visual Tab on the page/post editor no longer functions. It shows blank and doesn't show the toolbar and doesn't allow text to be entered. The text tab works fine. 

Here is a screenshot with 2015 Loaded: http://cl.ly/image/1J3u123q2o2e
Here is a screenshot immediately after with Trestle loaded: http://cl.ly/image/0q3M3l1a2L12
Here is a screenshot of text tab same setting as previous image: http://cl.ly/image/1v3M2s0t0L3A

Only adjustment I've made to the theme is to declare woo-commerce support in the functions file. Removing that doesn't seem to impact this issue.

**Comment by BraadMartin** [comment]
Hello @foodin65,

Thank you for bringing this issue to our attention. There was a bad path in the included BFA Library that was causing TinyMCE to crash, and this was causing the issue. I've just pushed out a new release 2.0.1 that includes a fix for the issue.

Please try version 2.0.1 and let us know if you have any more trouble. And thanks for using Trestle!

**Comment by foodin65** [comment]
You're welcome. I've tried it, it's fixed now.
