### ISSUE TITLE
Implement better retina logo solution

### ISSUE THREAD

**Issue by MickeyKay** [MIGHTYminnow/trestle#31]
Right now we're just spitting out one logo, when we need to use background-image, background-size, and the 4 following uploads:
* Desktop
* Desktop @2x
* Mobile
* Mobile @2x

**Comment by BraadMartin** [comment]
We can achieve this using RICG Responsive Images and outputting our logo using get_image_tag. We'll need to switch from storing the logo image as an src to an attachment ID though. I'll add this to our the milestones for our next release.
