### ISSUE TITLE
Page Builder Problems

### ISSUE THREAD

**Issue by neil** [MIGHTYminnow/trestle#44]
This is probably an edge case and I apologise for wasting your time but I like to use Trestle and Beaver Builder together.
Unfortunately I just discovered BB doesn't work with the most recent version of Trestle. If I revert to my previous copy of 1.0.0 everything works ok again.
I have examined the latest version of Trestle as best I can to try and work out what might be causing a conflict but no luck so far. It's odd because BB seems to work with other Genesis themes. 
When there is a problem it is usually to do with a script conflict.
Can you think off the top of your head what might have changed in the last couple of commits to make BB stop working?

**Comment by MickeyKay** [comment]
Hi Neil,

Any chance you could pass along a .zip of Beaver Builder so I can look into this? You can email it to me if that works, I just don't have a copy of this premium plugin. Thanks.

**Comment by BraadMartin** [comment]
Hello Neil,

Thank you for the report. We've just committed a fix to the master branch that should resolve the issue. Please try it out and let us know if you experience any more issues.

**Comment by neil** [comment]
Hi Braad and Mickey, thank you very much for fixing this. It's great to be able to use my favourite Genesis theme again!

cheers
Neil
