### ISSUE TITLE
New site with new version of trestle has accessibility links / and color problems

### ISSUE THREAD

**Issue by garethwatt** [MIGHTYminnow/trestle#63]
I wanted to clone an existing site so I installed the latest version of trestle and wordpress and then used my function and style.css files with the new site.

The changes in the customize theme administration area write colors to inline CSS which breaks the previous design. There is no way to turn off this option that I can find and you HAVE TO select a color. Transparent is not an option. This means that they all have to be overrided with !important CSS selectors for color.  This is very annoying that those color selections in the admin area can't be disabled. 

Also I never installed Genesis Accessibly however skip links were added to my site breaking the design. Using the Genesis Accessibly Plugin I can hide them but including accessibility CSS but I can't remove the skip links. 

I love trestle but I thought it was a boiler plate to develop from. Things should be kept simple and use standard wordpress conventions like the style.css file.

Please let me know if there is some way to disable these options.

Thanks

**Comment by jgonzo127** [comment]
Hi Gareth,

Thanks for your feedback! We are currently working on making a plugin to house these customizer options. We'll then be removing the color options from the core theme. We initially added these features to help our team develop more quickly internally. That being said, we want to uphold the boilerplate workflow of Trestle and let the stylesheet house all color and font options unless the user decides to install the customizer plugin. We should be making this change relatively soon. Thanks again.

-Jordan

**Comment by jgonzo127** [comment]
Hi again Gareth,

Go ahead and download the latest update. We removed the color options in the customizer and added the option the disable accessibility options in the Trestle Settings customizer panel.
